---
title: "TestingDoc"
author: "Lucas Lacambra"
date: "2025-06-26"
output: html_document
---

## Femur nii/nrrd comparison
```{r}
surface_mesh_filepath <- system.file("extdata", "test_CT_femur.stl",
                             package = "BoneDensityMapping")
surface_mesh <- import_mesh(surface_mesh_filepath)

femur_nii <- import_scan(system.file("extdata", "test_CT_hip.nii", package = "BoneDensityMapping"))
bone_scan_check(surface_mesh, femur_nii)
```

```{r}
femur_nrrd <- import_scan(system.file("extdata", "test_CT_hip.nrrd", package = "BoneDensityMapping"))
bone_scan_check(surface_mesh, femur_nrrd)
```

```{r}
surface_mesh_path <- system.file("extdata", "test_CT_femur.stl",
 package = "BoneDensityMapping")
surface_mesh <- import_mesh(surface_mesh_path)
landmark_path <- system.file("extdata", "test_femur.mrk.json",
    package = "BoneDensityMapping")
landmarks <- import_lmks(landmark_path)
nifti_path <- system.file("extdata", "test_CT_hip.nii",
    package = "BoneDensityMapping")
nifti <- import_scan(nifti_path)
mapped_coords <- surface_points_template(surface_mesh, landmarks, no_surface_sliders = 1000)
mat_peak <- surface_normal_intersect(surface_mesh, mapped_coords, normal_dist = 3.0,
    nifti)
colored_mesh <- color_mesh(surface_mesh, mapped_coords, mat_peak, maxi=2000, mini=0)
plot <- plot_mesh(colored_mesh, density_color = NULL, title = '.nii')
```

```{r}
nifti_path <- system.file("extdata", "test_CT_hip.nrrd",
    package = "BoneDensityMapping")
nifti <- import_scan(nifti_path)
mapped_coords <- surface_points_template(surface_mesh, landmarks, no_surface_sliders = 1000)
mat_peak <- surface_normal_intersect(surface_mesh, mapped_coords, normal_dist = 3.0,
    nifti, rev_y=FALSE)
colored_mesh <- color_mesh(surface_mesh, mapped_coords, mat_peak, maxi=2000, mini=0)
plot <- plot_mesh(colored_mesh, density_color = NULL, title = '.nrrd')
```

## Scaphoid nii/nrrd comparison
#bone scan check
```{r}
SCAP004_mesh <- import_mesh(system.file("extdata", "SCAP004.stl", package = "BoneDensityMapping"))
SCAP004_lmk <- import_lmks(system.file("extdata", "SCAP004_landmarks.fcsv", package = "BoneDensityMapping"))
SCAP004_nii <- import_scan(system.file("extdata", "SCAP004_resampled.nii", package = "BoneDensityMapping"))
bone_scan_check(SCAP004_mesh, SCAP004_nii)
```

```{r}
SCAP004_nrrd <- import_scan(system.file("extdata", "SCAP004_resampled.nrrd", package = "BoneDensityMapping"))
bone_scan_check(SCAP004_mesh, SCAP004_nii)
```

#graph 
```{r}
mapped_coords <- surface_points_template(SCAP004_mesh, SCAP004_lmk, no_surface_sliders = 1000)
mat_peak <- surface_normal_intersect(SCAP004_mesh, mapped_coords, normal_dist = 3.0,
   SCAP004_nii, rev_y=FALSE)
colored_mesh <- color_mesh(SCAP004_mesh, mapped_coords, mat_peak, maxi=2000, mini=0)
plot <- plot_mesh(colored_mesh, density_color = NULL, title = '.nii')
```

```{r}
mat_peak <- surface_normal_intersect(SCAP004_mesh, mapped_coords, normal_dist = 3.0,
   SCAP004_nrrd, rev_y=FALSE)
colored_mesh <- color_mesh(SCAP004_mesh, mapped_coords, mat_peak, maxi=2000, mini=0)
plot <- plot_mesh(colored_mesh, density_color = NULL, title = '.nrrd')
```

